Repository DorianLudm/Appli_Pompiers, pull requests merged in 2023-10, with the labels that each got.

#13 Bd
  BD/DB_Pompiers
  BD/creation.sql
  BD/destruction.sql
  BD/insertion.sql
  BD/trigger.sql
  site_web/app.py
  site_web/models.py
Labels: developpement, Base de données

#16 Maj cas d'utilisation avec les tags
  CasUtilisation.drawio
Labels: Aide à l'implémentation, Relation client

#17 Refonte mcd avec tags
  MCD_pompiers
Labels: Aide à l'implémentation, Relation client, Base de données

#18 Premier rendu, schématisation diverses
  .flaskenv
  CasUtilisation.drawio
  MCD_pompiers
  Maquettes/Ajouter compte.png
  Maquettes/Connexion.png
  Maquettes/ConnexionMobile.png
  Maquettes/GestionCompte.png
  Maquettes/GestionCompte2.png
  Maquettes/GestionDocument.png
  Maquettes/GestionDocumentExemple.png
  Maquettes/GestionDocumentMain.png
  Maquettes/PageAcceuilAdmin.png
  Maquettes/RechercheDocument.png
  Maquettes/RechercheDocumentMobile.png
  Rapports/Rapport_Semaine1.pdf
  diagramme_activite_pompiers.drawio
  site_web/__init__.py
  site_web/app.py
  site_web/views.py
Labels: Maquette, Aide à l'implémentation, Relation client, Base de données
