Repository DorianLudm/Appli_Pompiers, pull requests merged in 2024-02, with the labels that each got.

#78 Fix TAGs en double
  site_web/models.py
  site_web/views.py
Labels: bug

#80 Gestion tags
  site_web/models.py
  site_web/static/css/accueil_admin.css
  site_web/static/css/header.css
  site_web/static/css/recherche_tag.css
  site_web/static/img/colorPalette.png
  site_web/templates/accueil_admin.html
  site_web/templates/rechercheComptes.html
  site_web/templates/recherche_doc_admin.html
  site_web/templates/recherche_tags.html
  site_web/views.py
Labels: developpement

#86 Personnalisation des tags
  site_web/app.py
  site_web/static/js/personnalisationTags.js
  site_web/templates/recherche_tags.html
Labels: enhancement

#89 Enleve le tag suprimmer des tags actifs
  site_web/views.py
Labels: bug

#90 Fix nom des tags
  site_web/static/js/personnalisationTags.js
Labels: bug

#95 Recherche doc admin
  site_web/static/css/recherche_doc.css
  site_web/static/css/recherche_doc_admin.css
  site_web/templates/recherche_doc_admin.html
  site_web/views.py
Labels: Flask

#101 Refonte du header
  site_web/static/css/header.css
  site_web/templates/informations_utilisateur.html
Labels: Web (HTML/CSS)

#109 Création de la recherche sur la page des tags
  site_web/models.py
  site_web/templates/recherche_tags.html
  site_web/views.py
Labels: enhancement

#114 FIX CSS dû à la refonte du header
  site_web/static/css/ajout_compte.css
  site_web/static/css/header.css
  site_web/templates/modifierCompte.html
Labels: Web (HTML/CSS)
